# Data Backup Best Practice {#backup}

(Data backup technologies and best practice)
 
## Overview 
### Abstract:

### Objectives:
This unit will provide a brief introduction to backup problems and methods to solve them.

### Outcomes:
After working through this unit you ...

  * have a sensible and effective strategy for backing up your computer;
  * have demonstrated that you can recover data.

### Deliverables:
**Time management**: Before you begin, estimate how long it will take you to complete this unit. Then, record in your course journal: the number of hours you estimated, the number of hours you worked on the unit, and the amount of time that passed between start and completion of this unit.

**Journal**: Document your progress in your Course Journal. Some tasks may ask you to include specific items in your journal. Don't overlook these.

**Insights**: If you find something particularly noteworthy about this unit, make a note in your insights! page.


## Data backups
When was the last time you made a full backup of your computer's hard-drive? Too long ago? I thought so.

`r task_counter <- task_counter + 1`
## Task `r task_counter`

```{block, type="rmd-task"}
  1. Backup your hard-drive now.
```

Risk is probability times damage. The annualized probability of hard drive failure is on the order of 3%. This means about three of your classmates in this course will lose all their data this year. It is a bit better for solid state drives (SSD), perhaps only 0.3 failures per year. But what is the damage? All your essays, coursework, all the pictures on your computer, that email from your first love... There is no question you need to have plans in place to protect your data. After all, storage failure is not a question of if, but when.

Enterprise-scale data in bioinformatics labs need dedicated solution and that is actually an increasing problem. For your small scale, personal backup needs you have a variety of options;

  * Cloud backup may be bandwidth limited;
  * Mac OS X has things well covered with thier Time machine / Time capsule, I don't know what the best equivalent is for other systems;
  * off-machine storage in removable disk is a questionable startegy because everything that is not fully automatic is liable to fall victim to complecancy;
  * Whenever possible, make differential backups. And remember: NO backup is a backup unless recovery of data has been tested and shown to work.

`r task_counter <- task_counter + 1`
## Task `r task_counter`

```{block, type="rmd-task"}
  * Use this [Google Search](https://www.google.ca/search?q=backup+options&num=20&tbs=qdr:y) for links to recent articles about backup options.
  * Read a few articles that are relevant for your computer.
  * Decide on a backup strategy for your computer.
  * Implement your strategy.
  * Create a test file.
  * Backup your computer.
  * Delete your test file.
  * Recreate the file from your last backup.
```

## Self-evaluation
## Notes
## Further reading, links and resources
Use this Google Search for links to recent articles about backup options.
 
**If in doubt, ask!**<br>
If anything about this learning unit is not clear to you, do not proceed blindly but ask for clarification. Post your question on the course mailing list: others are likely to have similar problems. Or send an email to your instructor.

 
```{block2, type="rmd-original-history"}
<br>**Author**: Boris Steipe <boris.steipe@utoronto.ca> <br>
**Created**: 2017-08-05<br>
**Modified**: 2017-09-11<br>
Version: 1.0<br>
**Version history**:<br>
1.0 Completed to first live version<br>
0.2 Begin development from legacy material; points only<br>
0.1 Material collected from previous tutorial<br>
 
```

### Updated Revision history
```{r echo=FALSE}
source("./bcb420_books_helper_functions.R")
if (git2r::in_repository(".")) {
  knitr::kable(githistory2table(git2r::commits(repo = ".", path = knitr::current_input())))
} else {
  cat("No Git history available.")
}

```

