# Cargo Cult Science {#cargocult}

(Cargo Cult science, Cargo Cult bioinformatics)

## Overview 
### Abstract:
Not all activities lead to valuable outcomes and "Cargo Cult Science" is an important metaphor for a class of conceptual problems that are the hallmark of "poor science". The particular issue is that activites are causally disconnected from their claimed beneficial outcomes.

### Objectives:
This unit will:

  * introduce the metaphor of a "Cargo Cult", as applied to bioinformatics and science in general;
  * illustrate with examples;
  * discuss principles to avoid the problem.

### Outcomes:
After working through this unit you:

  * can identify "Cargo Cult"-type issues;
  * have contributed an example to our collection, and/or;
  * have contributed to the discussion in our collection;
  * are able to critically evaluate projects and activities regarding whether they can contribute to thier claimed value;
  * are able to propose improvements.

### Deliverables:
**Time management**: Before you begin, estimate how long it will take you to complete this unit. Then, record in your course journal: the number of hours you estimated, the number of hours you worked on the unit, and the amount of time that passed between start and completion of this unit.

**Journal**: Document your progress in your Course Journal. Some tasks may ask you to include specific items in your journal. Don't overlook these.

**Insights**: If you find something particularly noteworthy about this unit, make a note in your insights! page.

### Prerequisites:
You need the following preparation before beginning this unit. If you are not familiar with this material from courses you took previously, you need to prepare yourself from other information sources:

Inquiry: The scientific method; evidence based reasoning; how to design, execute and document an experiment; Conjecture, hypothesis and theory.
 
 
## Cargo Cult

The concept of [Cargo cult science](https://en.wikipedia.org/wiki/Cargo_cult_science) was popularized by [Richard Feynman](https://en.wikipedia.org/wiki/Richard_Feynman) in the 1974 [Caltech Commencement address](http://calteches.library.caltech.edu/51/2/CargoCult.htm). In a nutshell, Feynman points out how scientific practices that lack "scientific integrity" are similar to the activities of a premodern cult in the South Sea islands that developed rituals for attracting goods-bearing supply airplanes by building mock airports.

The essence of Cargo Cult is not merely poor science. What makes it "Cargo Cult" is a disconnect between form and contents: the form is compelling, but there can't be a rational expectation of a benefit from the activity because there is no causal connection between the activity and the claimed outcome. This is often, but not always due to [logical fallacies](https://en.wikipedia.org/wiki/List_of_fallacies).

The topic is interesting for bioinformatics because the deficiencies are often subtle, and hard for the non-expert to spot. To guard against Cargo Cult takes integrity, and practice. A structured approach may be helpful that first clearly identifies the hoped-for outcome, then defines the proposed activities, then asks in specific detail how the outcome would be caused by the activity. **Causation** is key here - many examples of Cargo Cult behaviour are based on a mistaken belief in causation, where actually merely a correlation was observed. But you have to be careful: the fact that causation has not been shown does not prove it is absent. And even if causation is absent, that does not automatically make the behaviour invalid: sometimes you are right for the wrong reason. Both cases are not Cargo Cult. Rather, it is characteristic for situations we should label as Cargo Cult that there "is no cargo in the system": you are looking in the wrong place, you don't have a control or reference value, you don't understand your data - or similar problems.
 
`r task_counter <- task_counter + 1`
## Task `r task_counter`

```{block, type="rmd-task"}
  1. Read a brief introduction to ideas about ["Cargo Cult Bioinformatics"](./boris_docs/FND-Cargo_Cult.pdf).
  1. Visit the [Student Wiki: Cargo_Cult_Science page](http://steipe.biochemistry.utoronto.ca/abc/students/index.php/Cargo_Cult_Science) (and its associated [Student Wiki: Not_(quite)_Cargo_Cult_Science](http://steipe.biochemistry.utoronto.ca/abc/students/index.php/Not_(quite)_Cargo_Cult_Science) page) on the Student Wiki and add an example of your own that you have encountered during your studies or elsewhere^[Make sure your example has not already been posted by someone else - it would be Cargo Cult to post it again.].
  1. Also, add to the discusssion of any of the existing examples. Comments that question whether the example actually should be called Cargo Cult, and that lead to improved focus and clarification are especially valuable.
```

## Self-evaluation

## Further reading, links and resources

  * [Student Contributions: Cargo Cult Examples](http://steipe.biochemistry.utoronto.ca/abc/students/index.php/Cargo_Cult_Science)
  * [Student Contributions: Not (quite) Cargo Cult Examples](http://steipe.biochemistry.utoronto.ca/abc/students/index.php/Not_(quite)_Cargo_Cult_Science)
  * [Wikipedia: List of Logical Fallacies](https://en.wikipedia.org/wiki/List_of_fallacies) a very comprehensive resource. One would wish that the presence of such a list itself would have a beneficial effect on science.
 
**If in doubt, ask!**<br>
If anything about this learning unit is not clear to you, do not proceed blindly but ask for clarification. Post your question on the course mailing list: others are likely to have similar problems. Or send an email to your instructor.

 
```{block2, type="rmd-original-history"}
<br>**Author**: Boris Steipe <boris.steipe@utoronto.ca> <br>
**Created**: 2017-08-05<br>
**Modified**: 2017-09-11<br>
Version: 1.1<br>
**Version history**:<br>
1.1 Add references to logical fallacies; review older submissions and move some into Not (quite) Cargo Cult page.<br>
1.0 Completed to first live version<br>
0.1 Material collected from previous tutorial<br>
 
```

### Updated Revision history
```{r echo=FALSE}
source("./bcb420_books_helper_functions.R")
if (git2r::in_repository(".")) {
  knitr::kable(githistory2table(git2r::commits(repo = ".", path = knitr::current_input())))
} else {
  cat("No Git history available.")
}

```

### Footnotes:
 


