# Technical Questions {#technial_questions}

(HInts for asking technical questions on mailing lists and forums)

## Overview 
### Abstract:
We all depend on others' insights and help to get computing done. But there are good ways to ask technical questions, that will lead to quick and useful answers, and other ways...

### Objectives:
This unit will:

  * direct you to three documents that discuss strategies for asking technical questions;

### Outcomes:
After working through this unit you:

  * are familar with effective strategies for asking technical questions;
  * understand the importance of MWE's (Minimal Working Examples);
  * have begun to model these principles in your own work for this course and elsewhere.

### Deliverables:
**Time management**: Before you begin, estimate how long it will take you to complete this unit. Then, record in your course journal: the number of hours you estimated, the number of hours you worked on the unit, and the amount of time that passed between start and completion of this unit.

**Journal**: Document your progress in your Course Journal. Some tasks may ask you to include specific items in your journal. Don't overlook these.

**Insights**: If you find something particularly noteworthy about this unit, make a note in your insights! page.

### Prerequisites:
You need the following preparation before beginning this unit. If you are not familiar with this material from courses you took previously, you need to prepare yourself from other information sources:

  * Writing: Basic essay and report writing skills. How to format your submitted materials, how to quote, cite and avoid plagiarism.

 
`r task_counter <- task_counter + 1`
## Task `r task_counter`

```{block, type="rmd-task"}
Study the following three documents:

  * the [R Help Mailing list posting guide](https://www.r-project.org/posting-guide.html)
  * [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/minimal-reproducible-example) – R advice via stackoverflow.
  * [How to Ask Questions the Smart Way for the technical minded](http://www.catb.org/~esr/faqs/smart-questions.html), excellent advice!
If you follow this advice, you can't go wrong.
```


## Self-evaluation

## Further reading, links and resources

**If in doubt, ask!**<br>
If anything about this learning unit is not clear to you, do not proceed blindly but ask for clarification. Post your question on the course mailing list: others are likely to have similar problems. Or send an email to your instructor.



```{block2, type="rmd-original-history"}
<br>**Author**: Boris Steipe <boris.steipe@utoronto.ca> <br>
**Created**: 2017-08-05<br>
**Modified**: 2017-09-11<br>
Version: 1.0<br>
**Version history**:<br>
1.0 Completed to first live version<br>
0.1 Material collected from previous assignments<br>
 
```

### Updated Revision history
```{r echo=FALSE}
source("./bcb420_books_helper_functions.R")
if (git2r::in_repository(".")) {
  knitr::kable(githistory2table(git2r::commits(repo = ".", path = knitr::current_input())))
} else {
  cat("No Git history available.")
}

```
 